sentence = ("Hello World")
print(len(sentence))
print(sentence[0])
print(sentence[0:5])
print(sentence[6:11])
print(sentence[:5])
print(sentence[6:])
print(sentence[-1])
print(sentence[:-3])
print(sentence[-3:])
