Total words - 61
Unique words - 43

= - 6
words - 3
in - 3
- - 3
import - 2
file - 2
file.close() - 2
for - 2
words[word.lower()] - 2
1 - 2
+ - 2
operator - 1
sys - 1
open(sys.argv[-1], - 1
"r") - 1
text - 1
file.read() - 1
{} - 1
word - 1
text.split(): - 1
if - 1
word.lower() - 1
words: - 1
+= - 1
else: - 1
sortedwords - 1
sorted(words.items(), - 1
key= - 1
operator.itemgetter(1), - 1
reverse=true) - 1
open(sys.argv[-1][:-4] - 1
"-count" - 1
sys.argv[-1][-4:], - 1
"w") - 1
file.write("total - 1
{}\nunique - 1
{}\n\n".format(len(text.split()), - 1
len(sortedwords))) - 1
wordinfo - 1
sortedwords: - 1
file.write("{} - 1
{}\n".format(wordinfo[0], - 1
wordinfo[1])) - 1
